services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb-crud-documents
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_crud_documents_data:/data/db
      - ./seed:/docker-entrypoint-initdb.d:ro

volumes:
  mongo_crud_documents_data:
