apiVersion: v1
kind: Service
metadata:
  name: 03-kubectl-commands-cheat-service
spec:
  type: NodePort
  selector:
    app: 03-kubectl-commands-cheat
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
