name: 03-GitHub-Actions-Environment-Variables Workflow
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Node Environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci --omit=dev
    - name: Run code validation
      run: npm run test --if-present
