apiVersion: v1
kind: Service
metadata:
  name: 04-kubernetes-service-nodeport-service
spec:
  type: NodePort
  selector:
    app: 04-kubernetes-service-nodeport
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
