apiVersion: v1
kind: Service
metadata:
  name: 05-configmaps-env-vars-service
spec:
  type: NodePort
  selector:
    app: 05-configmaps-env-vars
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
