const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const inputPath = path.join(root, "tokens", "tokens.json");
const outputPath = path.join(root, "src", "scss", "_tokens.scss");
const tokens = JSON.parse(fs.readFileSync(inputPath, "utf8"));

const lines = [
  "// Generated by scripts/compile-tokens.js",
  "// Do not edit manually when changing tokens.",
  ""
];

for (const [group, values] of Object.entries(tokens)) {
  for (const [name, value] of Object.entries(values)) {
    lines.push(`$${group}-${name}: ${value};`);
  }
  lines.push("");
}

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, `${lines.join("\n")}\n`);
console.log(`Generated ${path.relative(root, outputPath)}`);
