apiVersion: v1
kind: Service
metadata:
  name: 01-minikube-cluster-setup-service
spec:
  type: NodePort
  selector:
    app: 01-minikube-cluster-setup
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
