aws_region       = "us-east-1"
environment      = "staging"
project_name     = "study-platform"
instance_type    = "t3.micro"
db_name          = "studyapp"
db_username      = "studyadmin"
db_password      = "ChangeMe123!"
allowed_ssh_cidr = "203.0.113.10/32"
