apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pvc
  namespace: study-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
